name: Build(1.7.1_py3.8.13_cuda10.2_ubuntu18.04)

env:
  BASE_IMAGE: "ubuntu:18.04"

  PYTHON_VERSION: "3.8.13"

  PYTORCH_VERSION: "1.7.1"
  PYTORCH_VERSION_SUFFIX: ""
  TORCHVISION_VERSION: "0.8.2"
  TORCHVISION_VERSION_SUFFIX: ""
  TORCHAUDIO_VERSION: "0.7.2"
  TORCHAUDIO_VERSION_SUFFIX: ""
  PYTORCH_DOWNLOAD_URL: ""

  IMAGE_TAG: "1.7.1-py3.8.13-cuda10.2-ubuntu18.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_1.7.1_py3.8.13_cuda10.2_ubuntu18.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
