name: Build(2.7.1_py3.11.10_ubuntu22.04)

env:
  BASE_IMAGE: "ubuntu:22.04"

  PYTHON_VERSION: "3.11.10"

  PYTORCH_VERSION: "2.7.1"
  PYTORCH_VERSION_SUFFIX: "+cpu"
  TORCHVISION_VERSION: "0.22.1"
  TORCHVISION_VERSION_SUFFIX: "+cpu"
  TORCHAUDIO_VERSION: "2.7.1"
  TORCHAUDIO_VERSION_SUFFIX: "+cpu"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/"

  IMAGE_TAG: "2.7.1-py3.11.10-ubuntu22.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.7.1_py3.11.10_ubuntu22.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
