name: Build(1.6.0_py3.9.12_cuda10.1_devel_ubuntu18.04)

env:
  BASE_IMAGE: "nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04"

  PYTHON_VERSION: "3.9.12"

  PYTORCH_VERSION: "1.6.0"
  PYTORCH_VERSION_SUFFIX: "+cu101"
  TORCHVISION_VERSION: "0.7.0"
  TORCHVISION_VERSION_SUFFIX: "+cu101"
  TORCHAUDIO_VERSION: ""
  TORCHAUDIO_VERSION_SUFFIX: ""
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/torch_stable.html"

  IMAGE_TAG: "1.6.0-py3.9.12-cuda10.1-devel-ubuntu18.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_1.6.0_py3.9.12_cuda10.1_devel_ubuntu18.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
