name: Build(2.5.0_py3.10.15_cuda12.4.1_ubuntu22.04)

env:
  BASE_IMAGE: "ubuntu:22.04"

  PYTHON_VERSION: "3.10.15"

  PYTORCH_VERSION: "2.5.0"
  PYTORCH_VERSION_SUFFIX: "+cu124"
  TORCHVISION_VERSION: "0.20.0"
  TORCHVISION_VERSION_SUFFIX: "+cu124"
  TORCHAUDIO_VERSION: "2.5.0"
  TORCHAUDIO_VERSION_SUFFIX: "+cu124"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/"

  IMAGE_TAG: "2.5.0-py3.10.15-cuda12.4.1-ubuntu22.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.5.0_py3.10.15_cuda12.4.1_ubuntu22.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
